random_no=Math.floor((Math.random()*array_1.length)+1);
console.log(array_1[random_no]);
sketch=array_1[random_no];
document.getElementById("drawn_sketch").innerHTML=sketch;
timer_counter=0;
score=0;
timer_check;
drawn_sketch;
answer_holder;